# Generated by Django 3.2.5 on 2021-08-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210803_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
